spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/test
    username: root
    password: root
logging: 
  level: 
    root: info
    com: 
      cifibank:   
        dao: debug
